name: Release Charts

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Move index.yaml
        run: |
          git checkout gh-pages
          git pull
          mv index.yaml docs/index.yaml
          git add .
          git commit -m "move index.yaml"
          git push